import 'package:gettext/gettext.dart';

class MyLocale implements Translations {
  Map<String, Map<String, String>> get keys => {
    'ar': {
      '1': 'صفحة التصنيفات',
      '2': 'العربية',
      "3":  'الانكليزية',
      "4": "اختر اللغة",
      '5': 'المفضلة',
      '6': 'اللغة',
      '7': 'اضافة طلب',
      '8': 'رؤية طلباتي',
      '9': 'حولنا',
      '10': 'الخروج',
      '11': 'فارماسيا',
      '12': 'عرض',
      '13': 'بحث',
      '14': 'صفحة الأدوية',
      '15': 'تفاصيل',
      '16': 'الاسم العلمي',
      '17': 'الاسم التجاري',
      '18': 'السعر',
      '19': 'تاريخ الصلاحية',
      '20': 'شركة',
      '21': 'رجوع',
      '22': 'طلباتي',
      '23': 'الطلب رقم',
      '24': 'الحالة',
      '25': 'اسم الدواء',
      '26': 'الكمية المطلوبة',
      '27': 'تسجيل الدخول',
      '28': 'ادخل الرقم',
      '29': 'ادخل كلمة السر',
      '30': 'ليس لديك حساب ؟',
      '31': 'سجل الآن',
      '32': 'ربما ليس لديك حساب او ليس لديك اذن للتسجيل',
      '33': 'الرقم لا يجب ان يترك فارغا',
      '34': 'الرقم لا يجب ان يكون اطول ان من 10 ',
      '35': 'الرقم يجب ان يكون 10 خانات',
      '36': 'كلمة السر لا يجب ان تترك فارغة',
      '37': 'كلمة السر لا يجب ان تكون أقل من 8',
      '38': 'خطأ',
      '39': 'الغاء',
      '40': 'موافق',
      '41': 'تسجيل',
      '42':'ادخل اسم المستخدم',
      '43':'اسم المستخدم يجب ان لا يترك فارغا',
      '44':'تأكيد كلمة السر',
      '45':'تأكد ان كلمة السر التي ادخلتها هي ذاتها',
      '46':'فشل التسجيل',
      '47':'الرقم او اسم المستخدم موجود مسبقا',
      '48':'تنبيه',
      '49':'هل أنت متأكد أنك تريد الخروج',
      '50':'نعم',
      '51':'لا',
      '52':'الوضع الليلي',
      '53':'اللغة',
      '54':'اضافة طلب',
      '55':'الكمية',
      '56':'تم ارسال الطلب بنجاح',
      '57':'فشل ارسال الطلب',
      '58':'تم',
      '59':'نتائج البحث',
      '60':'لا يوجد نتيجة',
      '61':"المفضلة",
      '62':'هذا التطببيق تم تطويره لمساعدة الصيادلة في أعمالهم',
      '63':'المطورين',
      '64':'أسماء مفضي',
      '65':'ايمان بازرباشي',
      '66':'سلمى الفوال',
      '67':'عمر الميداني',
      '68':'عمر سقر',
      '69':'حول هذا التطبيق',
      '70':'حولنا'


    },
    'en': {
      "1": 'Categories Page',
      "2": 'ARABIC',
      '3': 'ENGLISH',
      "4": "Choose Language",
      '5': 'Favorites',
      '6': 'Language',
      '7': 'Add Order',
      '8': 'Show My Orders',
      '9': 'About Us',
      '10': 'Log Out',
      '11': 'Farmacia',
      '12': 'view',
      '13': 'Search',
      '14': 'Medicins Page',
      '15': 'Details',
      '16': 'Scintific Name',
      '17': 'Commerecial Name',
      '18': 'Price',
      '19': 'Expire Date',
      '20': 'Company',
      '21': 'Back',
      '22': 'My Orders',
      '23': 'Order Num',
      '24': 'State',
      '25': 'Medicine Name',
      '26': 'Required Quantity',
      '27': 'Login',
      '28': 'Enter Phonenumber',
      '29': 'Enter Password',
      '30': 'Don\'t have an Account ?',
      '31': 'Register Now',
      '32':
      'May you don\'t register or you don\'t have permission to login',
      '33': 'phonenumber must be not empty',
      '34': 'phonenumber can\'t be larger than 10',
      '35': 'phonenumber must be 10 numbers',
      '36': 'password must be not empty',
      '37': 'Password can\'t be less than 8',
      '38': 'Error',
      '39': 'Cancel',
      '40': 'Ok',
      '41': 'Register',
      '42':'Enter Username',
      '43':'username must br not empty',
      '44':'Confirm your password',
      '45':'Make sure that you are enter the same password',
      '46':'Register Faild',
      '47':'This Phonenumber and Username already exist',
      '48':'Attention',
      '49':'Are you sure that you want to logout ?',
      '50':'YES',
      '51':'No',
      '52':'Dark mode',
      '53':'Languge',
      '54':'Add Order',
      '55':'Quantity',
      '56':'Order Send Successfully',
      '57':"Faild To Send Order",
      '58':"Done",
      '59':'Results Page',
      '60':'No Result Found',
      "61":"My Favorite;",
      "62":"'This app was created to help  pharmacists in there jobs'",
      "63":'Developers',
      "64":'Asmaa Mufddi',
      "65":'Eyman BazerBashi',
      "66":'Salma Alfawal',
      "67":'Omar Mediani',
      "68":'Omar Saker',
      '69':'About this app',
      '70':'About Us'

    }
  };

  @override
  Map<String, Map<String, Translation>> get contexts =>
      throw UnimplementedError();

  @override
  Translation? getTranslation(String msgctxt, String msgid) {
    throw UnimplementedError();
  }
}
